//LOS GLOBAL OBJECTS SON OBJETOS PREDEFINIDOS QUE ESTAN DISPONIBLES EN TODOS LOS ENTORNOS DE EJECUCION DE JS

console.log(__dirname)  //DEVUELVE EN DONDE ESTA EL ARCHIVO GLOBAL .JS

console.log(__filename) //DEVUELVE LA RUTA COMPLETA

console.log(module) //DEVUELVE UN OBJETO DONDE HAY INFORMACION SOBRE EL MODULO ACTUAL EN EL QUE SE ENCUENTRA EL CODIGO DE JS

console.log(process) //DEVUELVE UN OBJETO CON INFORMACION DEL SISTEMA